name:                winapi-user32-sys
version:             0.1.0.0
github:              "jeiea/dal-hs"
license:             BSD3
author:              "jeiea"
maintainer:          "solum5013@gmail.com"
copyright:           "2019 jeiea"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeiea/dal-hs#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src
  include-dirs: include
  dependencies: winapi-common
  reexported-modules: winapi-common:Win32.Types
  extra-libraries:
    - user32
    - advapi32
    - gdi32
    - winmm
    - shell32
  when:
    - condition: os(windows) && arch(i386)
      then:
        cpp-options: -DWINDOWS_CCONV=stdcall
      else:
        cpp-options: -DWINDOWS_CCONV=ccall

tests:
  winapi-user32-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - winapi-user32-sys
