name:                dal
version:             0.1.0.0
github:              "jeiea/dal-hs"
license:             BSD3
author:              "jeiea"
maintainer:          "solum5013@gmail.com"
copyright:           "2019 jeiea"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeiea/dal-hs#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

flags:
  dev:
    description: Make subsystem to console for debugging.
    manual: False
    default: False

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - rio
    - winapi-kernel32-sys
    - winapi-user32-sys

executable:
  main: app/Main.hs
  dependencies: dal
  when:
    - condition: "!flag(dev)"
      ghc-options: -optl-Wl,--subsystem,windows

tests:
  dal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - winapi-user32-sys
